const travelData = [
  {
    name: "Araku Valley",
    state: "Andhra Pradesh",
    benefit: "Stress Relief & Nature Therapy",
    image: "https://th.bing.com/th/id/OIP.GG9_AgnS2J1_WMehmI4RSAHaE8?w=243&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Lambasingi",
    state: "Andhra Pradesh",
    benefit: "Cool Climate & Peaceful Environment",
    image: "https://th.bing.com/th/id/OIP.PAtmqAihgSnghnoNJLt3VgHaEU?w=300&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Horsley Hills",
    state: "Andhra Pradesh",
    benefit: "Mind Relaxation & Scenic Views",
    image: "https://www.hyderabadtourism.travel/images/popular/hill-stations-near-hyderabad/horsley-hills-near-hyderabad.jpg",
  },
  {
    name: "Munnar",
    state: "Kerala",
    benefit: "Relaxation & Fresh Air",
    image: "https://th.bing.com/th/id/OIP.PXjldzZcNzKEySYyrSBJggHaEK?w=265&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Wayanad",
    state: "Kerala",
    benefit: "Nature Healing & Forest Therapy",
    image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/405911153.jpg?k=af2ab931c8e070ba31475011829c9674569592dad9150f26a0bd64f990b07a60&o=&hp=1",
  },
  {
    name: "Varkala",
    state: "Kerala",
    benefit: "Beach Therapy & Mindfulness",
    image: "https://th.bing.com/th/id/OIP.Y9NgtDgeMBDnwarE3rJKAAHaE7?w=282&h=188&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Coorg",
    state: "Karnataka",
    benefit: "Mental Wellness & Nature Escape",
    image: "https://th.bing.com/th/id/OIP.fFlY-7ENabOBBLEPiPW0TAHaEX?w=308&h=182&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Gokarna",
    state: "Karnataka",
    benefit: "Beach Therapy & Peace",
    image: "https://tse4.mm.bing.net/th/id/OIP.aNi-_8R9MgllQjzQx51hWwHaE4?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Chikmagalur",
    state: "Karnataka",
    benefit: "Stress Relief & Coffee Estate Retreat",
    image: "https://th.bing.com/th/id/R.5265cb9354592771159b128e6a9503f0?rik=TtrnTjAV5qOw%2bA&riu=http%3a%2f%2f4.bp.blogspot.com%2f-oHQxC24gYS0%2fUXixVEbiYhI%2fAAAAAAAAPg0%2fywasVafvziY%2fs1600%2fchikmagalur_india_17371.JPEG&ehk=tb2uajKJ%2bbu4ZkqfBERt2ch8JNAAecpoBoCqSrGqNpk%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    name: "Rishikesh",
    state: "Uttarakhand",
    benefit: "Meditation & Spiritual Healing",
    image: "https://th.bing.com/th/id/OIP.y4QAfTwGkkd1zcHYRK1odQHaE7?w=280&h=187&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Nainital",
    state: "Uttarakhand",
    benefit: "Lake Views & Mental Refreshment",
    image: "https://www.holidify.com/images/cmsuploads/compressed/19421484519_dd4e3f4009_b_20190514143704.jpg",
  },
  {
    name: "Auli",
    state: "Uttarakhand",
    benefit: "Mountain Calm & Inner Peace",
    image: "https://thumbs.dreamstime.com/b/joshimath-auli-uttarakhand-nov-aerial-view-auli-famous-himalayan-ski-resort-hill-station-uttarakhand-india-auli-hill-260847007.jpg",
  },
  {
    name: "Manali",
    state: "Himachal Pradesh",
    benefit: "Mountain Escape & Relaxation",
    image: "https://tse2.mm.bing.net/th/id/OIP.j5TyC7oZZSX5HmUTJcRSIAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Dharamshala",
    state: "Himachal Pradesh",
    benefit: "Spiritual Healing & Mindfulness",
    image: "https://th.bing.com/th/id/OIP.6wCpphbGWdRpv4Ck5JPPkwHaEK?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Kasol",
    state: "Himachal Pradesh",
    benefit: "Digital Detox & Nature Therapy",
    image: "https://tse4.mm.bing.net/th/id/OIP.WTikoZe0Pm87Q23ou68JGwHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Shillong",
    state: "Meghalaya",
    benefit: "Fresh Air & Emotional Well-being",
    image: "https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2025/06/04171945/Places-to-visit-in-Shillong-FI.jpg",
  },
  {
    name: "Cherrapunji",
    state: "Meghalaya",
    benefit: "Nature Immersion & Relaxation",
    image: "https://tse1.mm.bing.net/th/id/OIP.RiaOOt1fVlkPQyn0qG_QXAHaFb?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Tawang",
    state: "Arunachal Pradesh",
    benefit: "Peaceful Monasteries & Reflection",
    image: "https://media.cntraveller.in/wp-content/uploads/2017/04/tawang-monastery.jpg",
  },
  {
    name: "Ziro Valley",
    state: "Arunachal Pradesh",
    benefit: "Calm Environment & Mental Clarity",
    image: "https://www.india.com/wp-content/uploads/2024/07/Explore-Ziro-Valley.jpg",
  },
  {
    name: "Auroville",
    state: "Tamil Nadu",
    benefit: "Meditation & Self-Discovery",
    image: "https://tse2.mm.bing.net/th/id/OIP.pP8E91Ozd-hST5xfUcmuOQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Kodaikanal",
    state: "Tamil Nadu",
    benefit: "Stress Reduction & Mountain Serenity",
    image: "https://media1.thrillophilia.com/filestore/330j1qdk2shkzvymsagpujnwk97d_shutterstock_377921479.jpg",
  },
  {
    name: "Ooty",
    state: "Tamil Nadu",
    benefit: "Cool Weather & Mental Relaxation",
    image: "https://images.hindustantimes.com/img/2023/01/11/1600x900/mugi-jo-6qUltw7SjzM-unsplash_1669276738103_1673425680248_1673425680248.jpg",
  },
  {
    name: "Palolem Beach",
    state: "Goa",
    benefit: "Beach Relaxation & Emotional Healing",
    image: "https://th.bing.com/th/id/OIP.-aDXq36bKMonyBuA8Vsi8wHaE5?w=264&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
  },
  {
    name: "Agonda Beach",
    state: "Goa",
    benefit: "Peaceful Solitude & Calmness",
    image: "https://tse2.mm.bing.net/th/id/OIP.5Wzz9TYayvq9B7lLcv7GhQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Mount Abu",
    state: "Rajasthan",
    benefit: "Quiet Hills & Mental Refreshment",
    image: "https://tse1.mm.bing.net/th/id/OIP.pUCEyBqxNxRKTuaPFPvxZAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Pachmarhi",
    state: "Madhya Pradesh",
    benefit: "Nature Walks & Stress Relief",
    image: "https://vl-prod-static.b-cdn.net/system/images/000/695/823/912291ec3c8e103355422c30aa0579fa/x600gt/pachmahri_adventure_geek.jpg?1691554980",
  },
  {
    name: "Valley of Flowers",
    state: "Uttarakhand",
    benefit: "Natural Beauty & Happiness Boost",
    image: "https://th.bing.com/th/id/OIP.rA8E3XP83yLHWf-gSt5j5gHaE0?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    benefit: "Inner Peace & Self Reflection",
    image: "https://media1.thrillophilia.com/filestore/zgu7fgfjy5e275mfrwhw21sujkmz_shutterstock_2361426719.jpg",
  },
  {
    name: "Majuli",
    state: "Assam",
    benefit: "Cultural Healing & Tranquility",
    image: "https://th.bing.com/th/id/OIP.ofzXZYAnlMmz6-rERH6hJQAAAA?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Pangong Lake",
    state: "Ladakh",
    benefit: "Mental Clarity & Scenic Therapy",
    image: "https://static.toiimg.com/photo/msid-79549873,width-96,height-65.cms",
  },
];

export default travelData;